/**
 * @file    ledconf.c
 * @brief
 *
 * @{
 */

#include "ledconf.h"

struct LedSetting LED1[] =
{
        {LED_COMPNENTORDER_GRB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_GRB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_GRB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_GRB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_GRB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_RGB},
        {LED_COMPNENTORDER_GRB},
};


/** @} */
